FROM nvidia/cuda:12.0.0-cudnn8-devel-ubuntu22.04

ENV DEBIAN_FRONTEND=noninteractive

ARG HTTP_PROXY
ARG HTTPS_PROXY

ENV http_proxy=${HTTP_PROXY}
ENV https_proxy=${HTTPS_PROXY}

RUN apt-get update && apt-get install -y \
    ca-certificates \
    apt-transport-https \
    software-properties-common \
    build-essential \
    git \
    wget \
    gnupg \
    pkg-config \
    ninja-build \
    libpng-dev \
    libjpeg-dev \
    libtiff-dev \
    libxxf86vm1 \
    libxxf86vm-dev \
    libxi-dev \
    libxrandr-dev \
    graphviz \
    libopencv-dev \
    libceres-dev \
    libboost-all-dev \
    libatlas-base-dev \
    libglfw3-dev \
    libmpfr-dev \
    libgmp-dev  \
    qtbase5-dev \
    qt5-qmake \
    libqt5svg5-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /opt
RUN apt-get update && apt-get install -y \
    && wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null \
    && echo 'deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ jammy main' | tee /etc/apt/sources.list.d/kitware.list >/dev/null \
    && apt-get update \
    && apt-get install -y cmake \
    && cmake --version \
    && rm -rf /var/lib/apt/lists/*

RUN wget https://developer.nvidia.com/downloads/compute/machine-learning/tensorrt/10.8.0/local_repo/nv-tensorrt-local-repo-ubuntu2204-10.8.0-cuda-12.8_1.0-1_amd64.deb \
    && dpkg -i nv-tensorrt-local-repo-ubuntu2204-10.8.0-cuda-12.8_1.0-1_amd64.deb \
    && cp /var/nv-tensorrt-local-repo-ubuntu2204-10.8.0-cuda-12.8/*-keyring.gpg /usr/share/keyrings/ \
    && apt-get update \
    && apt-get install -y tensorrt \
    && rm -rf /var/lib/apt/lists/* \
    && rm nv-tensorrt-local-repo-ubuntu2204-10.8.0-cuda-12.8_1.0-1_amd64.deb

WORKDIR /opt
RUN wget https://github.com/CGAL/cgal/releases/download/v6.0.1/CGAL-6.0.1.tar.xz \
    && tar -xvf CGAL-6.0.1.tar.xz \
    && cd CGAL-6.0.1 \
    && cmake . && make install \
    && rm -r /opt/CGAL-6.0.1/

WORKDIR /opt
RUN git clone --recursive https://github.com/shioko-chan/openMVG_SuperPoint-LightGlue.git \
    && cd openMVG_SuperPoint-LightGlue \
    && git submodule update --init --recursive \
    && mkdir openMVG_Build \
    && cd openMVG_Build \
    && cmake -DCMAKE_BUILD_TYPE=Release \
    -DOpenMVG_BUILD_TESTS=ON \
    -DOpenMVG_BUILD_EXAMPLES=OFF \
    ../src \
    && cmake --build . --parallel $(nproc) \
    && cmake --install . 

WORKDIR /opt
RUN git clone --recurse-submodules https://github.com/cdcseacave/openMVS.git \
    && git clone -b devel https://github.com/cnr-isti-vclab/vcglib.git \
    && mkdir openMVS/openMVS_Build \
    && cd openMVS/openMVS_Build \
    && cmake .. \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_LIBRARY_PATH=/usr/local/cuda/lib64/stubs \
    -DVCG_ROOT=/opt/vcglib \
    -DEigen3_DIR=/usr/local/share/eigen3/cmake \
    -DCGAL_DIR=/opt/CGAL-6.0.1 \
    && cmake --build . --parallel $(nproc) \
    && cmake --install . \
    && mv /usr/local/bin/OpenMVS/* /usr/local/bin/

COPY ./models /models

WORKDIR /opt
ENTRYPOINT [ "/bin/bash" ]