FROM nvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04

ENV DEBIAN_FRONTEND=noninteractive

ARG HTTP_PROXY
ARG HTTPS_PROXY

ENV http_proxy=${HTTP_PROXY}
ENV https_proxy=${HTTPS_PROXY}

# Install basic packages
RUN apt-get update && apt-get install -y \
    ca-certificates apt-transport-https software-properties-common \
    build-essential gnupg pkg-config ninja-build \
    wget curl zip unzip tar git \
    libpng-dev libjpeg-dev libtiff-dev libxxf86vm1 libxxf86vm-dev \
    libxi-dev libxrandr-dev \
    libopencv-dev libceres-dev libboost-all-dev \
    libatlas-base-dev libglfw3-dev libmpfr-dev libgmp-dev  \
    && rm -rf /var/lib/apt/lists/*

# Install CMake
WORKDIR /opt
RUN wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null \
    && echo 'deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ jammy main' | tee /etc/apt/sources.list.d/kitware.list >/dev/null \
    && apt-get update && apt-get install -y cmake \
    && rm -rf /var/lib/apt/lists/*

# Install ONNXRuntime
WORKDIR /opt
RUN wget https://github.com/microsoft/onnxruntime/releases/download/v1.21.0/onnxruntime-linux-x64-gpu-1.21.0.tgz \
    && tar -xvf onnxruntime-linux-x64-gpu-1.21.0.tgz \
    && cd onnxruntime-linux-x64-gpu-1.21.0 \
    && cp -r ./* /usr/local/ \
    && rm -r /opt/onnxruntime/ /opt/onnxruntime-linux-x64-gpu-1.21.0.tgz

# Install Dependi CGAL
WORKDIR /opt
RUN wget https://github.com/CGAL/cgal/releases/download/v6.0.1/CGAL-6.0.1.tar.xz \
    && tar -xvf CGAL-6.0.1.tar.xz \
    && cd CGAL-6.0.1 \
    && cmake . && make install \
    && rm -r /opt/CGAL-6.0.1/ /opt/CGAL-6.0.1.tar.xz

# Install OpenMVG
WORKDIR /opt
RUN git clone --recursive https://github.com/shioko-chan/openMVG_SuperPoint-LightGlue.git \
    && cd openMVG_SuperPoint-LightGlue \
    && git submodule update --init --recursive \
    && mkdir openMVG_Build \
    && cd openMVG_Build \
    && cmake -DCMAKE_BUILD_TYPE=Release \
    -DOpenMVG_BUILD_TESTS=ON \
    -DOpenMVG_BUILD_EXAMPLES=OFF \
    ../src \
    && cmake --build . --parallel $(nproc) \
    && cmake --install . 

# Install OpenMVS
WORKDIR /opt
RUN git clone --recurse-submodules https://github.com/cdcseacave/openMVS.git \
    && git clone -b devel https://github.com/cnr-isti-vclab/vcglib.git \
    && mkdir openMVS/openMVS_Build \
    && cd openMVS/openMVS_Build \
    && cmake .. \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_LIBRARY_PATH=/usr/local/cuda/lib64/stubs \
    -DVCG_ROOT=/opt/vcglib \
    -DEigen3_DIR=/usr/local/share/eigen3/cmake \
    -DCGAL_DIR=/opt/CGAL-6.0.1 \
    && cmake --build . --parallel $(nproc) \
    && cmake --install . \
    && mv /usr/local/bin/OpenMVS/* /usr/local/bin/

COPY models /models

WORKDIR /opt
ENTRYPOINT [ "/bin/bash" ]