FROM nvidia/cuda:11.8.0-cudnn8-devel-ubuntu20.04

ENV DEBIAN_FRONTEND=noninteractive

ARG HTTP_PROXY
ARG HTTPS_PROXY

ENV http_proxy=${HTTP_PROXY}
ENV https_proxy=${HTTPS_PROXY}


RUN apt-get update && apt-get install -y \
    wget \
    build-essential \
    cmake \
    ninja-build \
    curl \
    git \
    vim \
    libssl-dev \
    zlib1g-dev \
    pkg-config \
    libboost-all-dev \
    libfftw3-dev \
    libopencv-dev \
    libcgal-dev \
    libcgal-qt5-dev \
    && rm -rf /var/lib/apt/lists/*


RUN mkdir -p /opt/onnxruntime && \
    wget https://github.com/microsoft/onnxruntime/releases/download/v1.16.1/onnxruntime-linux-x64-gpu-1.16.1.tgz -O /tmp/onnxruntime.tgz && \
    tar -xzf /tmp/onnxruntime.tgz -C /opt/onnxruntime --strip-components=1 && \
    rm /tmp/onnxruntime.tgz

ENV LD_LIBRARY_PATH=/opt/onnxruntime/lib:$LD_LIBRARY_PATH

RUN git clone https://github.com/shioko-chan/stiching.git /stitching

WORKDIR /stitching

RUN mkdir -p /imgs

COPY ../imgs /imgs

CMD ["/bin/bash"]